<?php
	$config = array(
		"image" => "https://i.imgur.com/kkl8HuK.jpg",
		"sign" => "https://i.imgur.com/bvkaSPp.png",
		"name" => "Chaitra Chandra",
		"desc" => "Personal Portfolio of Chaitra Chandra, a JavaScript Full Stack Developer.",
		"role" => "Full Stack Developer",
		"freelancing" => "I am available for freelance",
		"profile" => array(
			"subheading" => "I'm a <strong>JavaScript Full Stack Developer</strong> from India. I aim to make a difference through my creative solution.",
			"para" => implode("</p><p>", array(
			    "I'm a JavaScript developer with an interest in building the most efficient website possible. Currently getting my hands dirty on React JS &amp; Node JS",
                "I have serious passion for UI effects, creating intuitive, dynamic user experiences.",
                "I have been a web developer for about an year and I am currently looking for internship opportunities."
			)),
			"addr" => " 71 Alyestone Road, LE27LL, Leicester, England, UK.",
			"phone" => "+44 7469309216",
			"interests" => "Coding, Programming, Developing",
			"bday" => "10 January 1995",
			"email" => "me@chaithra.me",
			"skype" => "chaitra",
		),
		"skills" => array(
			array("Javascript", "3", 95), // Duplicate this line and add your own values.
			array("React JS", "2", 85),
			array("Node JS", "2", 85),
			array("MongoDB", "2", 70),
			array("HTML5", "2", 75),
			array("CSS3", "2", 60)
		),
		"experience" => array(
			array(
				"Data Analyst",
				"AxisRooms Travel Distribution Ltd",
				'Jan 2017 - June 2017',
				"Developed an application that stores the data exchanged between two systems."
			),
			array(
				"Marketing Executive",
				"S.R Fashions",
				'July 2017 - November 2018',
				"Represented the company in various client meets, presentations and conferences as well provided the insights to managing the team that made the work efficient and robust."
			)
		),
		"education" => array(
			array(
				"Cloud Computing MSc",
				"Univeristy of Leicester",
				"Jan 2019 - Present",
				"This course covers the theoretical aspects of Computer Software and its Applications with basics of cloud computing concepts like agile cloud automation, Internet and networking with workshop experience."
			),
		),
		"social" => array(
			"linkedin" => "https://www.linkedin.com/in/chaitra-chandra-564a61129/",
			"facebook" => "https://www.facebook.com/profile.php?id=100008780987557",
			"instagram-outline" => "https://www.instagram.com/chaithrachandra/",
			"octocat" => "https://github.com/chaitraa",
		)
	);
?>